apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- "onepassword-connect-token-store.yaml"

helmCharts:
- name: connect
  repo: https://1password.github.io/connect-helm-charts
  version: 1.13.0
  releaseName: connect
  namespace: onepassword
  valuesInline:
    connect:
      credentialsName: onepassword-connect-server-credentials
