apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik
  repo: https://helm.traefik.io/traefik
  version: 25.0.0
  releaseName: traefik
  namespace: traefik
  valuesFile: values.yaml
