---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
controllers:
  flaresolverr:
    containers:
      app:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: v3.3.16
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          PROMETHEUS_ENABLED: "true"

service:
  web:
    enabled: true
    controller: flaresolverr
    ports:
      http:
        port: 80
        targetPort: 8191
  metrics:
    controller: flaresolverr
    ports:
      metrics:
        port: 8192
