apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "namespace.yaml"
  - "https://github.com/kubernetes-sigs/node-feature-discovery/deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml?ref=v0.14.3"
  - "https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/operator/crd?ref=v0.28.0"
  - "node-feature-rule.yaml"

helmCharts:
  - name: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: 0.14.3
    releaseName: node-feature-discovery
    namespace: intel
  - name: intel-device-plugins-operator
    repo: https://intel.github.io/helm-charts
    version: 0.28.0
    releaseName: intel-device-plugins-operator
    namespace: intel
  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts
    version: 0.28.1-helm.0
    releaseName: intel-device-plugins-gpu
    namespace: intel
    valuesInline:
      name: gpudeviceplugin-default
      sharedDevNum: 2
      nodeFeatureRule: true

patches:
- patch: |-
    apiVersion: deviceplugin.intel.com/v1
    kind: GpuDevicePlugin
    metadata:
      name: gpudeviceplugin-default
    spec:
      resourceManager: null
  target:
    kind: GpuDevicePlugin
    name: "gpudeviceplugin-default"