---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
controllers:
  overseerr:
    containers:
      app:
        image:
          repository: ghcr.io/linuxserver/overseerr
          tag: 1.33.2
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"

service:
  overseerr:
    enabled: true
    controller: overseerr
    annotations:
      external-dns.alpha.kubernetes.io/hostname: overseerr.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 5055

ingress:
  overseerr:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cloudflare
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: overseerr.mcmahan.io
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: overseerr
              port: http
    tls:
      - secretName: 'overseerr-cert'
        hosts:
          - overseerr.mcmahan.io

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 1Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      overseerr:
        app:
          - path: /config
