---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "namespace.yaml"

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: v1.13.0
    releaseName: rook-release
    namespace: rook-ceph
    valuesInline:
      enableDiscoveryDaemon: true
  - name: rook-ceph-cluster
    repo: https://charts.rook.io/release
    version: v1.13.0
    releaseName: rook-release
    namespace: rook-ceph
    valuesInline:
      toolbox:
        enabled: true
      cephObjectStores: []
